[package]
name = "advent-of-code-rs"
version = "0.1.0"
authors = ["Cesar D. Velandia <cesar@velandia.co>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
